[build]
  command = "bin/bridgetown deploy && bin/netlify.sh"
  publish = "output"

[build.lifecycle]
preinstall = """
  echo '📦 Preinstall started'
  mise install ruby 3.4.1 python 3.12.3
  mise use --global ruby 3.4.1
  mise use --global python 3.12.3
  mise which ruby
  mise which gem
  mise which bundle
  ruby -v
  gem -v
  bundler -v || true
  echo '✅ Preinstall done'
"""


[build.environment]
  NODE_ENV = "development"
  BRIDGETOWN_ENV = "production"
  MISE_EXPERIMENTAL = "0"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=604800, s-max-age=604800"

[[headers]]
  for = "/"
  [headers.values]
    Link = [
      "<CSS_PATH>; rel=preload; as=style",
      "<JS_PATH>; rel=preload; as=script",
      "<https://NETLIFY_IMAGES_CDN_DOMAIN>; rel=preconnect"
    ]

[[headers]]
  for = "/*.(png|jpg|js|css|svg|woff|ttf|eot|ico|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-max-age=31536000"
